-- HexaContext synthetic manufacturing dataset v1.
-- Runtime tables contain ordinary source records only. Evaluation labels live in
-- the unexposed private_eval schema created by the following migration.

create table public.dataset_snapshots (
  snapshot_id text primary key,
  dataset_id text not null,
  dataset_version text not null,
  as_of_time timestamptz not null,
  synthetic boolean not null check (synthetic),
  contains_real_company_or_client_data boolean not null
    check (not contains_real_company_or_client_data),
  record_manifest_hash text not null check (record_manifest_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  unique (dataset_id, dataset_version)
);

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  organization_name text not null,
  synthetic boolean not null check (synthetic),
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (tenant_id <> '' and organization_name <> ''),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, snapshot_id),
  unique (id, tenant_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id)
);

create table public.sites (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  site_name text not null,
  timezone text not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (tenant_id <> '' and site_id <> '' and site_name <> ''),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, site_id, snapshot_id),
  unique (id, tenant_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, snapshot_id)
    references public.organizations(tenant_id, snapshot_id)
);

create table public.suppliers (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  supplier_id text not null,
  supplier_name text not null,
  supplier_status text not null check (supplier_status in ('APPROVED', 'CONDITIONAL', 'INACTIVE')),
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (tenant_id <> '' and site_id <> '' and supplier_id <> '' and supplier_name <> ''),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, supplier_id, snapshot_id),
  unique (id, tenant_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.parts (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  part_id text not null,
  part_number text not null,
  part_family text not null,
  description text not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (tenant_id <> '' and site_id <> '' and part_id <> '' and part_number <> ''),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, part_id, snapshot_id),
  unique (tenant_id, part_number, snapshot_id),
  unique (id, tenant_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.equipment (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  equipment_id text not null,
  equipment_code text not null,
  equipment_type text not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (tenant_id <> '' and site_id <> '' and equipment_id <> '' and equipment_code <> ''),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, equipment_id, snapshot_id),
  unique (tenant_id, equipment_code, snapshot_id),
  unique (id, tenant_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.manufacturing_lots (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  lot_id text not null,
  lot_number text not null,
  part_id text not null,
  supplier_id text not null,
  inspection_equipment_id text not null,
  observed_part_revision text not null,
  quantity integer not null check (quantity > 0),
  manufactured_at timestamptz not null,
  status text not null check (status in ('MANUFACTURED', 'INSPECTED', 'RELEASED', 'QUARANTINED')),
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, lot_id, snapshot_id),
  unique (tenant_id, lot_number, snapshot_id),
  unique (id, tenant_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id),
  foreign key (tenant_id, part_id, snapshot_id)
    references public.parts(tenant_id, part_id, snapshot_id),
  foreign key (tenant_id, supplier_id, snapshot_id)
    references public.suppliers(tenant_id, supplier_id, snapshot_id),
  foreign key (tenant_id, inspection_equipment_id, snapshot_id)
    references public.equipment(tenant_id, equipment_id, snapshot_id)
);

create table public.inspections (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  inspection_id text not null,
  lot_id text not null,
  inspection_type text not null,
  result text not null check (result in ('ACCEPTED', 'FAILED', 'CONDITIONAL')),
  critical_defect_count integer not null check (critical_defect_count >= 0),
  major_defect_count integer not null check (major_defect_count >= 0),
  minor_defect_count integer not null check (minor_defect_count >= 0),
  inspector_alias text not null,
  completed_at timestamptz not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, inspection_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, lot_id, snapshot_id)
    references public.manufacturing_lots(tenant_id, lot_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.certificates_of_analysis (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  certificate_id text not null,
  lot_id text not null,
  certificate_number text not null,
  verification_status text not null check (verification_status in ('VERIFIED', 'UNVERIFIED', 'INVALID')),
  issuer_name text not null,
  issued_at timestamptz not null,
  verified_at timestamptz,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, certificate_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, lot_id, snapshot_id)
    references public.manufacturing_lots(tenant_id, lot_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.calibration_records (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  calibration_id text not null,
  equipment_id text not null,
  calibration_status text not null check (calibration_status in ('VALID', 'EXPIRED', 'SUSPENDED')),
  calibrated_at timestamptz not null,
  valid_until timestamptz not null,
  standard_reference text not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (valid_until > calibrated_at),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, calibration_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, equipment_id, snapshot_id)
    references public.equipment(tenant_id, equipment_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.engineering_revisions (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  revision_id text not null,
  part_id text not null,
  revision_code text not null,
  release_status text not null check (release_status in ('RELEASED', 'SUPERSEDED', 'DRAFT')),
  released_at timestamptz,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, revision_id, snapshot_id),
  unique (tenant_id, part_id, revision_code, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, part_id, snapshot_id)
    references public.parts(tenant_id, part_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.supplier_quality_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  quality_event_id text not null,
  supplier_id text not null,
  part_id text not null,
  related_lot_number text not null,
  outcome text not null check (outcome in ('PASS', 'FAIL')),
  failure_category text,
  event_at timestamptz not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check ((outcome = 'FAIL') or failure_category is null),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, quality_event_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, supplier_id, snapshot_id)
    references public.suppliers(tenant_id, supplier_id, snapshot_id),
  foreign key (tenant_id, part_id, snapshot_id)
    references public.parts(tenant_id, part_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.deviations (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  deviation_id text not null,
  lot_id text,
  part_id text,
  supplier_id text,
  equipment_id text,
  status text not null check (status in ('OPEN', 'APPROVED', 'CLOSED', 'CANCELLED')),
  severity text not null check (severity in ('LOW', 'MEDIUM', 'HIGH')),
  opened_at timestamptz not null,
  closed_at timestamptz,
  description text not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (num_nonnulls(lot_id, part_id, supplier_id, equipment_id) > 0),
  check (closed_at is null or closed_at >= opened_at),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, deviation_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, lot_id, snapshot_id)
    references public.manufacturing_lots(tenant_id, lot_id, snapshot_id),
  foreign key (tenant_id, part_id, snapshot_id)
    references public.parts(tenant_id, part_id, snapshot_id),
  foreign key (tenant_id, supplier_id, snapshot_id)
    references public.suppliers(tenant_id, supplier_id, snapshot_id),
  foreign key (tenant_id, equipment_id, snapshot_id)
    references public.equipment(tenant_id, equipment_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.manufacturing_notes (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  note_id text not null,
  lot_id text,
  part_id text,
  equipment_id text,
  note_type text not null check (note_type in ('SHIFT_NOTE', 'INSPECTION_NOTE', 'HR_NOTE')),
  body text not null,
  signed_by_alias text not null,
  signed_at timestamptz not null,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['general']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  fts tsvector generated always as (
    to_tsvector('english'::regconfig, coalesce(note_type, '') || ' ' || coalesce(body, ''))
  ) stored,
  check (num_nonnulls(lot_id, part_id, equipment_id) > 0),
  check (body <> ''),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  unique (tenant_id, note_id, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, lot_id, snapshot_id)
    references public.manufacturing_lots(tenant_id, lot_id, snapshot_id),
  foreign key (tenant_id, part_id, snapshot_id)
    references public.parts(tenant_id, part_id, snapshot_id),
  foreign key (tenant_id, equipment_id, snapshot_id)
    references public.equipment(tenant_id, equipment_id, snapshot_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);

create table public.decision_profiles (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  site_id text not null,
  profile_id text not null,
  profile_version text not null,
  task_type text not null,
  required_evidence_classes jsonb not null,
  freshness_rules jsonb not null,
  source_precedence jsonb not null,
  hold_rules jsonb not null,
  escalation_rules jsonb not null,
  retrieval_limits jsonb not null,
  active_from timestamptz not null,
  active_to timestamptz,
  snapshot_id text not null references public.dataset_snapshots(snapshot_id),
  source_system text not null,
  source_record_id text not null,
  source_version text not null,
  authority text not null,
  observed_at timestamptz not null,
  effective_from timestamptz not null,
  effective_to timestamptz,
  required_scopes text[] not null default array['quality']::text[],
  content_hash text not null,
  created_at timestamptz not null default now(),
  check (active_to is null or active_to > active_from),
  check (effective_to is null or effective_to > effective_from),
  check (cardinality(required_scopes) > 0),
  check (content_hash ~ '^[0-9a-f]{64}$'),
  check (jsonb_typeof(required_evidence_classes) = 'object'),
  check (jsonb_typeof(freshness_rules) = 'object'),
  check (jsonb_typeof(source_precedence) = 'object'),
  check (jsonb_typeof(hold_rules) = 'array'),
  check (jsonb_typeof(escalation_rules) = 'array'),
  check (jsonb_typeof(retrieval_limits) = 'object'),
  unique (tenant_id, profile_id, profile_version, snapshot_id),
  unique (tenant_id, snapshot_id, source_system, source_record_id),
  foreign key (tenant_id, site_id, snapshot_id)
    references public.sites(tenant_id, site_id, snapshot_id)
);
